apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Values.app.namespace }} 
spec:
  replicas: {{ int .Values.app.replicaCount }} 
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Version }}"
  template: 
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: {{ .Values.app.containerName | quote }}
        image: "{{ .Values.image.name }}:{{ .Values.image.version }}" 
        resources:
          requests:
            memory: {{ .Values.resources.reqMem | quote }} 
            cpu: {{ .Values.resources.reqCPU | quote }}
          limits:
            memory: {{ .Values.resources.maxMem | quote }} 
            cpu: {{ .Values.resources.maxCPU | quote }}
        ports:
        {{- if .Values.server }}
        - containerPort: {{ default 80 .Values.server.containerPort }} 
        {{- end }}
