apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
  namespace: {{ .Values.app2.namespace }}
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: website2
