app:
  namespace: website
  replicaCount: 5
  containerName: website-container
image:
  name: 192.168.0.106:32002/repository/toast-docker/comicbox 
  version: v1
resources: 
  reqMem: 128Mi 
  reqCPU: 50m 
  maxMem: 128Mi 
  maxCPU: 100m
server: 
  containerPort: 3000
service:
  name: website-svc
  type: NodePort
  port: 3000



app2:
  namespace: website2
  replicaCount: 5
  containerName: website-container2
  image: 192.168.0.106:32002/repository/toast-docker/website2
  version: v1
  port: 80

service2:
  name: website2-svc
  type: NodePort
  port: 80
